#pragma once

#include <filesystem>
#include <istream>
#include <string>
#include <string_view>

#include "core/quantity_kind.hpp"
#include "core/session.hpp"

namespace core
{
    //
    // A stimulus file: what a script should read, written by a person (or
    // generated by a tool) rather than captured from a rig.
    //
    //     # Everything a script reads, and what it should get.
    //     Output5V          = 5.01 V                  # always, however often it is read
    //     Output5V.Vmin     = 4.85 V, 4.80 V          # one per read, in order
    //     Osc1.Acquisition  = true
    //     Ser1.Data         = <41 43 4B 0D 08>
    //     Osc1.Channel3     = trace( V, -0.001 s, 1e-06 s, "dip.samples")
    //
    // ---------------------------------------------------------------------
    // Why this is not the recording format
    // ---------------------------------------------------------------------
    //
    // A recording (see core/recording.hpp) is a run artifact whose only reader
    // is --replay. It is deliberately flat, positional and machine-oriented, it
    // carries a sequence number and a wall clock nobody authoring one has an
    // opinion about, and -- the part that matters -- it cannot say the single
    // most useful thing an author wants to say. Every value in a recording is
    // consumed once, in order, because that is what faithfully reproducing a
    // run means. "This point reads 5.01 V however many times the script looks
    // at it" is not expressible in it at all, and a --repeat=50 run would need
    // fifty copies of every row.
    //
    // Both files remain useful and neither replaces the other: capture a run to
    // reproduce it exactly, author one to describe a DUT that does not exist
    // yet, or a fault that is hard to provoke on the bench.
    //
    // ---------------------------------------------------------------------
    // The two rules worth knowing
    // ---------------------------------------------------------------------
    //
    // ONE VALUE IS STICKY; A LIST IS A SEQUENCE. That is not a quirk of this
    // parser -- it is the distinction the injection API has always drawn, and
    // this file is spelled to match it exactly:
    //
    //     Measure.inject( "Output5V", 5.01_V);              Output5V = 5.01 V
    //     Read.inject( "Ser1.Data", { "ACK\r", "0xF5\r" }); Ser1.Data = "ACK\r", "0xF5\r"
    //
    // A sticky value never runs out. A list runs out, and running past its end
    // throws -- a script reading more times than the file answers for has
    // diverged from what the author expected, which is the thing worth failing
    // on (see core::detail::ObservationSlots).
    //
    // A VALUE IS SPELLED THE WAY A LOG SPELLS IT. The payload forms here are
    // core::describeValue's output, character for character -- "ACK\r" for text,
    // <1B 5B 41> for anything with a byte in it that is not text. So the way to
    // find out what to write is to read it off the log line of a run that did
    // it, and paste it in. Same for a reading: the log says "5.021 V" and that
    // is what goes on the right of the '='.
    //
    // ---------------------------------------------------------------------
    // The grammar, in full
    // ---------------------------------------------------------------------
    //
    //   line     := comment | blank | 'key = value {, value}'
    //   comment  := '#' to end of line (also allowed after a value)
    //   key      := the session key, no whitespace -- "Output5V", "Ser1.Data",
    //               "Osc1.Acquisition". Run --skeleton to get the list.
    //
    //   value    := quantity | flag | payload | trace
    //   quantity := number [symbol]     5.01 V | 115 V | 1e-06 s | 0.95
    //   flag     := 'true' | 'false'
    //   payload  := '"' text '"'        "ACK\r"      escapes: \r \n \t \\ \"
    //             | '<' hex '>'         <1B 5B 41>   or <> for an empty reply
    //   trace    := 'trace(' symbol ',' quantity ',' quantity ',' samples ')'
    //   samples  := '[' number... ']'   inline, whitespace separated
    //             | '"' path '"'        one number per line or whitespace
    //                                   separated, relative to this file
    //
    // The unit symbols are exactly core::quantities' own -- V A W VA Ohm s dB
    // Hz var, and nothing at all for the one dimensionless kind. No prefixed
    // spellings (no mV, no us): this file's unit vocabulary IS that list, so
    // there is no second table to keep in step with it, and 1e-06 s says
    // unambiguously what "1us" would have had to be translated into anyway.
    //
    // Which seam a key is programmed on comes from the shape of its value, not
    // from anything about its name -- the same way a recording's rows are
    // sorted by which alternative they hold. Mixing shapes in one list is an
    // error: a point answers one kind of question.
    //
    // Samples in a file rather than a generator vocabulary (no ramp(), no
    // pulse(), no sine()), deliberately. Those would be a specification
    // language of their own, invented here, covering whichever four shapes
    // happened to be needed first; a list of numbers covers every shape, and is
    // what a scope export, a spreadsheet, a script or a model already produces.
    //

    //
    // Programs everything the stimulus describes into the bank, and arms it.
    //
    // Through the bank's own inject* methods -- the same seam a script unit
    // test uses -- so a stimulus file can do nothing a test could not have done
    // by hand, and cannot reach any state the injection API does not already
    // allow.
    //
    // Additive: a key not mentioned keeps whatever it had, so a stimulus file
    // can be layered over a loaded recording to change one reading and leave
    // the rest of a captured run alone.
    //
    // baseDirectory is what a trace's sample-file path is resolved against --
    // the stimulus file's own directory, so that a file and its samples move
    // together.
    //
    // Throws std::runtime_error naming the line and its number on anything
    // malformed. Nothing is programmed on failure being reached part way
    // through, which is worth knowing rather than relying on: a run armed from
    // half a stimulus file would fail somewhere unrelated to the typo.
    //
    auto injectStimulus(
        SessionBank &                  bank,
        std::istream &                 in,
        const std::filesystem::path &  baseDirectory = {}) -> void;

    //
    // The same, from a path, with baseDirectory taken from it.
    //
    auto injectStimulusFromFile( SessionBank & bank, const std::filesystem::path & path) -> void;

    //
    // The unit symbol a quantity of this kind is written with -- "V", "s", and
    // "" for the dimensionless one.
    //
    // Derived from the unit tags in core/quantity.hpp rather than restated, so
    // this cannot fall out of step with what describeValue prints. Public
    // because a caller writing a stimulus file (or a message about one) needs
    // the same spellings this parser accepts.
    //
    [[nodiscard]]
    auto unitSymbol( QuantityKind kind) -> std::string_view;

    //
    // The kind written with that symbol, or std::nullopt if no unit uses it.
    // The empty symbol answers the dimensionless kind, which is what makes a
    // bare number in a stimulus file mean something rather than being rejected.
    //
    [[nodiscard]]
    auto quantityKindFromSymbol( std::string_view symbol) -> std::optional<QuantityKind>;
} // namespace core
