#include "core/criteria/criteria_variants.hpp"

#include <algorithm>
#include <array>
#include <stdexcept>
#include <string>

//
// The variant names, and this build's default, handed in as compile definitions
// by framework/core/CMakeLists.txt. Defaulted here rather than left to fail, so core
// still compiles for a consumer that pulls this library in without a criteria
// layer at all -- with a single obviously-placeholder variant rather than an
// empty list, since every caller below would otherwise have to handle "no
// variants exist" as a case, and there is nothing useful for any of them to do
// about it. The same reasoning journal.cpp's "unknown" defaults follow.
//
#ifndef THORIUM_CRITERIA_VARIANT_NAMES
    #define THORIUM_CRITERIA_VARIANT_NAMES "core/criteria/detail/no_criteria_variants.inc"
#endif

#ifndef THORIUM_DEFAULT_CRITERIA_VARIANT
    #define THORIUM_DEFAULT_CRITERIA_VARIANT "unknown"
#endif

#ifndef THORIUM_MASTER_CRITERIA_VARIANT
    #define THORIUM_MASTER_CRITERIA_VARIANT "unknown"
#endif

namespace core
{
    namespace
    {
        //
        // Generated by cmake/CriteriaVariants.cmake from the one validated
        // THORIUM_KNOWN_CRITERIA_VARIANTS list -- flat content with no
        // scaffolding of its own, the same convention dut/criteria_*.inc
        // follows, so this array declaration is what supplies the context.
        //
        constexpr std::string_view Names[] = {
            #include THORIUM_CRITERIA_VARIANT_NAMES
        };

        //
        // Resolved once, at first use, rather than looked up per call: the
        // default's *name* is what the build stamps in, but everything
        // downstream wants its index.
        //
        // A default that is not in the list would mean the build definitions
        // disagree with each other, which the top-level CMakeLists.txt already
        // rejects at configure time -- falling back to 0 here rather than
        // throwing keeps a core built standalone (no criteria layer, hence no
        // matching default) from failing at static-init time for a facility it
        // is never going to use.
        //
        auto defaultIndex() -> std::size_t
        {
            const auto found = std::ranges::find( Names, std::string_view( THORIUM_DEFAULT_CRITERIA_VARIANT));

            return ( found == std::ranges::end( Names))
                ? 0u
                : static_cast<std::size_t>( found - std::ranges::begin( Names));
        }

        struct Selection
        {
            std::size_t  Index{ defaultIndex() };
            bool         Locked{ false };
        };

        //
        // Function-local rather than a namespace-scope object: Names above is
        // constexpr, but defaultIndex() is not, and a namespace-scope Selection
        // would then be subject to static initialisation order against every
        // other translation unit that might read it. A run's very first Verify
        // would be the place that bit.
        //
        auto selection() -> Selection &
        {
            static Selection state;

            return state;
        }
    } // namespace

    auto criteriaVariantNames() -> std::span<const std::string_view>
    {
        return Names;
    }

    auto defaultCriteriaVariantName() -> std::string_view
    {
        return Names[ defaultIndex()];
    }

    //
    // Returned as the build stamped it, not looked up in Names first. The
    // configure step already rejects a master that is not one of the known
    // variants, and a traceability field is the last place to launder a value
    // that disagrees with the build into a plausible-looking one -- the same
    // reasoning behind the "unknown" fallback above.
    //
    auto masterCriteriaVariantName() -> std::string_view
    {
        return THORIUM_MASTER_CRITERIA_VARIANT;
    }

    auto activeCriteriaVariant() -> std::size_t
    {
        return selection().Index;
    }

    auto activeCriteriaVariantName() -> std::string_view
    {
        return Names[ selection().Index];
    }

    auto selectCriteriaVariant( const std::string_view name) -> bool
    {
        auto & state = selection();

        if( state.Locked)
        {
            throw std::logic_error(
                "the criteria variant was changed after the run began; it must be selected "
                "before core::journal().begin() -- see core/criteria/criteria_variants.hpp");
        }

        const auto found = std::ranges::find( Names, name);

        if( found == std::ranges::end( Names))
        {
            return false;
        }

        state.Index = static_cast<std::size_t>( found - std::ranges::begin( Names));

        return true;
    }

    auto lockCriteriaVariant() -> void
    {
        selection().Locked = true;
    }

    auto resetCriteriaVariantForTesting() -> void
    {
        selection() = Selection{};
    }
} // namespace core
