#
# Generates the two files that turn THORIUM_KNOWN_CRITERIA_VARIANTS -- one
# CMake list, validated once -- into something C++ can see.
#
# The variant list has to reach the compiler somehow, and there are only bad
# ways to do that by hand: an #ifdef chain in a header (which is the raw,
# untyped environment-variable read the top-level CMakeLists.txt's own comment
# rejects), or a hand-maintained C++ list beside the CMake one (two lists that
# can disagree, and the disagreement is silent). Generating both files means
# adding a variant is still a one-line edit to one list, and everything that
# needs to know follows from it.
#
# Two files rather than one, because two very different consumers need two very
# different things and neither should acquire the other's dependencies:
#
#   criteria_variant_tables.inc  -- every variant's CRITERIA/CRIT table, each in
#       its own namespace, plus the `master` alias and the master table's path.
#       Read by core/criteria/active_criteria.hpp, i.e. by every script
#       translation unit. Pulls in the whole predicate/quantity vocabulary.
#
#   criteria_variant_names.inc   -- just the names, as string literals. Read by
#       core/src/criteria/criteria_variants.cpp (the runtime --criteria= selector) and by
#       nothing else. Deliberately free of any criteria content: the selector
#       needs to know what the legal names are, not what any of them mean.
#
# Both are written only when their content actually changes, so an ordinary
# reconfigure doesn't touch a file that every script includes and trigger a
# full rebuild for nothing.
#

#
# file(WRITE) unconditionally rewrites, which updates the mtime whether or not
# anything changed -- and these are files the whole scripts layer #includes.
# Compared against what's on disk first, so a no-op reconfigure is genuinely a
# no-op for the build.
#
function(_thorium_write_if_changed path content)
    set(existing "")

    if(EXISTS "${path}")
        file(READ "${path}" existing)
    endif()

    if(NOT existing STREQUAL "${content}")
        file(WRITE "${path}" "${content}")
        message(STATUS "Generated: ${path}")
    endif()
endfunction()

#
# variants:    the known variant names, in order (THORIUM_KNOWN_CRITERIA_VARIANTS)
# master:      which of them is the master table (THORIUM_CRITERIA_MASTER)
# criteriaDir: where criteria_<name>.inc files live (dut/)
# outputDir:   where to write the two generated files
#
# Sets THORIUM_CRITERIA_VARIANT_TABLES and THORIUM_CRITERIA_VARIANT_NAMES in the
# caller's scope, holding the two absolute paths.
#
function(thorium_generate_criteria_variants variants master criteriaDir outputDir)
    #
    # The master is the variant CRIT_FROM_MASTER borrows from and the table the
    # merged criteria are generated from (see core/criteria/active_criteria.hpp's
    # pass 2). Naming one that isn't in the list would otherwise fail at some
    # unrelated .inc file's first use of the macro, with an error naming neither
    # this list nor that requirement. Checked here, where the list actually is.
    #
    if(NOT "${master}" IN_LIST variants)
        message(FATAL_ERROR
            "THORIUM_CRITERIA_MASTER='${master}' is not one of "
            "THORIUM_KNOWN_CRITERIA_VARIANTS: ${variants}")
    endif()

    #
    # `master` is the alias emitted below, so a variant of that name would alias
    # itself. A deployment is free to call its master anything else -- production,
    # nominal, golden -- which is the whole point of the variable.
    #
    if("master" IN_LIST variants)
        message(FATAL_ERROR
            "A criteria variant cannot be named 'master': that name is the alias "
            "core/criteria/criterion.hpp's CRIT_FROM_MASTER resolves through. Rename it "
            "and point THORIUM_CRITERIA_MASTER at the new name.")
    endif()

    set(header "//\n// GENERATED by cmake/CriteriaVariants.cmake -- do not edit.\n//\n// Regenerated from THORIUM_KNOWN_CRITERIA_VARIANTS and THORIUM_CRITERIA_MASTER in\n// the top-level CMakeLists.txt on every reconfigure. See\n// core/criteria/active_criteria.hpp for what reads this and what it does with it.\n//\n\n")

    #
    # --- Pass 1: every variant's table, one namespace each ---
    # Nested inside thorium::criteria rather than at global scope so the group
    # structs (FS_Supply_1, ...) don't land there N times over -- only the
    # merged table generated from these does, which is what scripts name.
    #
    # The namespaces are siblings, which is what makes CRIT_FROM_MASTER's
    # deliberately-unqualified `master::group::id` resolve from inside any of
    # them: ordinary lookup walks out to thorium::criteria and finds the alias.
    #
    set(tables "${header}namespace thorium::criteria\n{\n")

    #
    # The master's table is emitted FIRST, whatever position it holds in the
    # list, and the alias right after it. Both halves matter:
    #
    #   - the alias is what keeps the master's *name* out of C++ entirely.
    #     CRIT_FROM_MASTER pastes the fixed token `master` (see
    #     core/criteria/criterion.hpp), so no header names a variant and this
    #     variable is the only place the choice is made;
    #   - the order is not cosmetic. Every other variant's CRIT_FROM_MASTER rows
    #     read `master::group::id` at namespace scope, so the master's groups
    #     have to be complete types by then -- emitting in list order works only
    #     while the master happens to come first in it, and fails with an
    #     incomplete-type error the moment it doesn't.
    #
    # Only the *declaration* order changes. THORIUM_FOR_EACH_CRITERIA_VARIANT
    # below still iterates the list as given, because those indices are the ones
    # --criteria= and core::criteriaVariantNames() agree on.
    #
    set(emissionOrder "${master}")

    foreach(variant IN LISTS variants)
        if(NOT "${variant}" STREQUAL "${master}")
            list(APPEND emissionOrder "${variant}")
        endif()
    endforeach()

    foreach(variant IN LISTS emissionOrder)
        set(incFile "${criteriaDir}/criteria_${variant}.inc")

        #
        # Checked at configure time rather than left to the preprocessor. A
        # variant named in the list with no file behind it otherwise surfaces as
        # a missing-include error inside a generated file, pointing at neither
        # the list that named it nor the directory it was expected in.
        #
        if(NOT EXISTS "${incFile}")
            message(FATAL_ERROR
                "Criteria variant '${variant}' is in THORIUM_KNOWN_CRITERIA_VARIANTS but "
                "${incFile} does not exist")
        endif()

        #
        # The master is what CRIT_FROM_MASTER borrows *from*, so using it there
        # asks a criterion to initialise itself from itself. Left to the
        # compiler that surfaces as an incomplete-type error inside a generated
        # file, naming neither the macro nor the reason -- and it is now a
        # reachable mistake rather than an impossible one, since any variant can
        # be the master and the other tables are full of that macro.
        #
        # Matched as an invocation at the start of a line, not as a substring:
        # these files talk about the macro in their comments (dev/dut's single
        # table does, and it is the master of that deployment), and a bare
        # substring search fails them for a sentence.
        #
        if("${variant}" STREQUAL "${master}")
            file(READ "${incFile}" masterContent)

            if(masterContent MATCHES "(^|\n)[ \t]*CRIT_FROM_MASTER[ \t]*\\(")
                message(FATAL_ERROR
                    "${incFile} is the master table (THORIUM_CRITERIA_MASTER=${master}) but uses "
                    "CRIT_FROM_MASTER, which borrows from the master itself. The master has to "
                    "spell every criterion out with CRIT -- it is also the table the merged "
                    "criteria are generated from. Either write those rows out in full, or point "
                    "THORIUM_CRITERIA_MASTER at the variant that already does.")
            endif()
        endif()

        string(APPEND tables
            "    namespace ${variant}\n"
            "    {\n"
            "        using namespace core::quantities;\n"
            "        using namespace core::literals;\n"
            "\n"
            "        #include \"${incFile}\"\n"
            "    }\n\n")

        if("${variant}" STREQUAL "${master}")
            string(APPEND tables "    namespace master = ${master};\n\n")
        endif()
    endforeach()

    string(APPEND tables "} // namespace thorium::criteria\n\n")

    #
    # --- The master table's path, for the merge pass to re-read ---
    # Emitted here rather than handed to the compiler as a second definition
    # beside THORIUM_CRITERIA_VARIANT_TABLES: the master is chosen by the same
    # variable that decides the alias above, and having framework/runner spell
    # the filename out a second time is how the two drift apart.
    #
    string(APPEND tables
        "//\n"
        "// The master variant's own table -- core/criteria/active_criteria.hpp re-reads it\n"
        "// with CRITERIA/CRIT redefined to build the merged table scripts name.\n"
        "//\n"
        "#define THORIUM_CRITERIA_MASTER_FILE \"${criteriaDir}/criteria_${master}.inc\"\n\n")

    #
    # --- The variant list, as something the preprocessor can iterate ---
    # An X-macro rather than anything cleverer because the thing being repeated
    # is a *token* (a namespace name pasted next to a group or CRIT identifier),
    # and the preprocessor is the only stage that can still do that. The
    # trailing __VA_ARGS__ is how the caller threads the group/id token through
    # to each expansion -- see core/criteria/active_criteria.hpp's merge pass.
    #
    string(APPEND tables
        "//\n"
        "// X( index, namespace, <caller's extra tokens>) once per known variant,\n"
        "// in THORIUM_KNOWN_CRITERIA_VARIANTS order -- the same order\n"
        "// core::criteriaVariantNames() reports, so an index means the same thing\n"
        "// on both sides.\n"
        "//\n"
        "#define THORIUM_FOR_EACH_CRITERIA_VARIANT( X, ...) \\\n")

    set(index 0)
    list(LENGTH variants variantCount)

    foreach(variant IN LISTS variants)
        math(EXPR nextIndex "${index} + 1")

        if(nextIndex EQUAL variantCount)
            set(continuation "\n")
        else()
            set(continuation " \\\n")
        endif()

        string(APPEND tables "    X( ${index}, ::thorium::criteria::${variant}, __VA_ARGS__)${continuation}")

        set(index ${nextIndex})
    endforeach()

    string(APPEND tables "\n#define THORIUM_CRITERIA_VARIANT_COUNT ${variantCount}\n")

    #
    # --- The names, for the runtime selector ---
    # Flat content with no scaffolding of its own -- no #pragma once, no
    # includes, not even a surrounding brace -- the same convention
    # dut/criteria_*.inc and rig/instrument.inc follow: whatever includes it
    # supplies the context. Here that context is an array initialiser.
    #
    set(names "${header}")

    foreach(variant IN LISTS variants)
        string(APPEND names "    \"${variant}\",\n")
    endforeach()

    file(MAKE_DIRECTORY "${outputDir}")

    set(tablesPath "${outputDir}/criteria_variant_tables.inc")
    set(namesPath  "${outputDir}/criteria_variant_names.inc")

    _thorium_write_if_changed("${tablesPath}" "${tables}")
    _thorium_write_if_changed("${namesPath}"  "${names}")

    set(THORIUM_CRITERIA_VARIANT_TABLES "${tablesPath}" PARENT_SCOPE)
    set(THORIUM_CRITERIA_VARIANT_NAMES  "${namesPath}"  PARENT_SCOPE)
endfunction()
