#
# Generates the two files that turn THORIUM_KNOWN_CRITERIA_VARIANTS -- one
# CMake list, validated once -- into something C++ can see.
#
# The variant list has to reach the compiler somehow, and there are only bad
# ways to do that by hand: an #ifdef chain in a header (which is the raw,
# untyped environment-variable read the top-level CMakeLists.txt's own comment
# rejects), or a hand-maintained C++ list beside the CMake one (two lists that
# can disagree, and the disagreement is silent). Generating both files means
# adding a variant is still a one-line edit to one list, and everything that
# needs to know follows from it.
#
# Two files rather than one, because two very different consumers need two very
# different things and neither should acquire the other's dependencies:
#
#   criteria_variant_tables.inc  -- every variant's CRITERIA/CRIT table, each in
#       its own namespace. Read by core/active_criteria.hpp, i.e. by every
#       script translation unit. Pulls in the whole predicate/quantity
#       vocabulary.
#
#   criteria_variant_names.inc   -- just the names, as string literals. Read by
#       core/src/criteria_variants.cpp (the runtime --criteria= selector) and by
#       nothing else. Deliberately free of any criteria content: the selector
#       needs to know what the legal names are, not what any of them mean.
#
# Both are written only when their content actually changes, so an ordinary
# reconfigure doesn't touch a file that every script includes and trigger a
# full rebuild for nothing.
#

#
# file(WRITE) unconditionally rewrites, which updates the mtime whether or not
# anything changed -- and these are files the whole scripts layer #includes.
# Compared against what's on disk first, so a no-op reconfigure is genuinely a
# no-op for the build.
#
function(_thorium_write_if_changed path content)
    set(existing "")

    if(EXISTS "${path}")
        file(READ "${path}" existing)
    endif()

    if(NOT existing STREQUAL "${content}")
        file(WRITE "${path}" "${content}")
        message(STATUS "Generated: ${path}")
    endif()
endfunction()

#
# variants:    the known variant names, in order (THORIUM_KNOWN_CRITERIA_VARIANTS)
# criteriaDir: where criteria_<name>.inc files live (dut/)
# outputDir:   where to write the two generated files
#
# Sets THORIUM_CRITERIA_VARIANT_TABLES and THORIUM_CRITERIA_VARIANT_NAMES in the
# caller's scope, holding the two absolute paths.
#
function(thorium_generate_criteria_variants variants criteriaDir outputDir)
    #
    # CRIT_FROM_PRODUCTION (see core/criterion.hpp) resolves an unqualified
    # `production::group::id`, so a variant set without a "production" in it
    # would fail at some unrelated .inc file's first use of the macro, with an
    # error naming neither this list nor that requirement. Checked here, where
    # the list actually is.
    #
    if(NOT "production" IN_LIST variants)
        message(FATAL_ERROR
            "THORIUM_KNOWN_CRITERIA_VARIANTS must include 'production': it is the baseline "
            "CRIT_FROM_PRODUCTION borrows from, and the reference table the merged "
            "criteria are generated from. Got: ${variants}")
    endif()

    set(header "//\n// GENERATED by cmake/CriteriaVariants.cmake -- do not edit.\n//\n// Regenerated from THORIUM_KNOWN_CRITERIA_VARIANTS in the top-level\n// CMakeLists.txt on every reconfigure. See core/active_criteria.hpp for what\n// reads this and what it does with it.\n//\n\n")

    #
    # --- Pass 1: every variant's table, one namespace each ---
    # Nested inside thorium::criteria rather than at global scope so the group
    # structs (FS_Supply_1, ...) don't land there N times over -- only the
    # merged table generated from these does, which is what scripts name.
    #
    # The namespaces are siblings, which is what makes CRIT_FROM_PRODUCTION's
    # deliberately-unqualified `production::group::id` resolve from inside any
    # of them: ordinary lookup walks out to thorium::criteria and finds it.
    #
    set(tables "${header}namespace thorium::criteria\n{\n")

    foreach(variant IN LISTS variants)
        set(incFile "${criteriaDir}/criteria_${variant}.inc")

        #
        # Checked at configure time rather than left to the preprocessor. A
        # variant named in the list with no file behind it otherwise surfaces as
        # a missing-include error inside a generated file, pointing at neither
        # the list that named it nor the directory it was expected in.
        #
        if(NOT EXISTS "${incFile}")
            message(FATAL_ERROR
                "Criteria variant '${variant}' is in THORIUM_KNOWN_CRITERIA_VARIANTS but "
                "${incFile} does not exist")
        endif()

        string(APPEND tables
            "    namespace ${variant}\n"
            "    {\n"
            "        using namespace core::quantities;\n"
            "        using namespace core::literals;\n"
            "\n"
            "        #include \"${incFile}\"\n"
            "    }\n\n")
    endforeach()

    string(APPEND tables "} // namespace thorium::criteria\n\n")

    #
    # --- The variant list, as something the preprocessor can iterate ---
    # An X-macro rather than anything cleverer because the thing being repeated
    # is a *token* (a namespace name pasted next to a group or CRIT identifier),
    # and the preprocessor is the only stage that can still do that. The
    # trailing __VA_ARGS__ is how the caller threads the group/id token through
    # to each expansion -- see core/active_criteria.hpp's merge pass.
    #
    string(APPEND tables
        "//\n"
        "// X( index, namespace, <caller's extra tokens>) once per known variant,\n"
        "// in THORIUM_KNOWN_CRITERIA_VARIANTS order -- the same order\n"
        "// core::criteriaVariantNames() reports, so an index means the same thing\n"
        "// on both sides.\n"
        "//\n"
        "#define THORIUM_FOR_EACH_CRITERIA_VARIANT( X, ...) \\\n")

    set(index 0)
    list(LENGTH variants variantCount)

    foreach(variant IN LISTS variants)
        math(EXPR nextIndex "${index} + 1")

        if(nextIndex EQUAL variantCount)
            set(continuation "\n")
        else()
            set(continuation " \\\n")
        endif()

        string(APPEND tables "    X( ${index}, ::thorium::criteria::${variant}, __VA_ARGS__)${continuation}")

        set(index ${nextIndex})
    endforeach()

    string(APPEND tables "\n#define THORIUM_CRITERIA_VARIANT_COUNT ${variantCount}\n")

    #
    # --- The names, for the runtime selector ---
    # Flat content with no scaffolding of its own -- no #pragma once, no
    # includes, not even a surrounding brace -- the same convention
    # dut/criteria_*.inc and rig/instrument.inc follow: whatever includes it
    # supplies the context. Here that context is an array initialiser.
    #
    set(names "${header}")

    foreach(variant IN LISTS variants)
        string(APPEND names "    \"${variant}\",\n")
    endforeach()

    file(MAKE_DIRECTORY "${outputDir}")

    set(tablesPath "${outputDir}/criteria_variant_tables.inc")
    set(namesPath  "${outputDir}/criteria_variant_names.inc")

    _thorium_write_if_changed("${tablesPath}" "${tables}")
    _thorium_write_if_changed("${namesPath}"  "${names}")

    set(THORIUM_CRITERIA_VARIANT_TABLES "${tablesPath}" PARENT_SCOPE)
    set(THORIUM_CRITERIA_VARIANT_NAMES  "${namesPath}"  PARENT_SCOPE)
endfunction()
