#
# Runs at build time (see framework/webui/CMakeLists.txt's add_custom_command)
# -- turns the console page's files under framework/webui/static/ into one
# .cpp that defines webui::staticFiles() (see src/static_content.hpp), so the
# served page is compiled into thorium_webui rather than read from disk.
#
# Each file becomes an unsigned char array, not a raw string literal. A raw
# string would read better in the generated file, but nobody reads that file,
# and it has two ways to break that an array has not: a delimiter the content
# happens to contain, and a compiler's limit on the length of one literal.
#
# EMBED_ROOT    -- the directory the files are served from
# EMBED_INPUTS  -- the files, as a ;-list; each is served at "/" + its path
#                  relative to EMBED_ROOT, so static/js/run.js is /js/run.js
# EMBED_OUTPUT  -- the .cpp to write
#
foreach(required EMBED_ROOT EMBED_INPUTS EMBED_OUTPUT)
    if(NOT ${required})
        message(FATAL_ERROR "${required} is empty or unset -- pass it with -D")
    endif()
endforeach()

set(arrays "")
set(entries "")
set(index 0)
foreach(input IN LISTS EMBED_INPUTS)
    file(RELATIVE_PATH name "${EMBED_ROOT}" "${input}")
    if(name MATCHES "^\\.\\./")
        message(FATAL_ERROR "${input} is not under EMBED_ROOT (${EMBED_ROOT})")
    endif()
    get_filename_component(extension "${input}" LAST_EXT)

    # Served with a charset: the page is UTF-8 (the tree's carets are not
    # ASCII), and a browser guessing otherwise is how they turn into mojibake.
    if(extension STREQUAL ".html")
        set(type "text/html; charset=utf-8")
    elseif(extension STREQUAL ".css")
        set(type "text/css; charset=utf-8")
    elseif(extension STREQUAL ".js")
        set(type "text/javascript; charset=utf-8")
    else()
        message(FATAL_ERROR "${input}: no content type for '${extension}' -- add one here")
    endif()

    file(READ "${input}" hex HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n        " bytes "${bytes}")

    string(APPEND arrays "    // ${name}\n    const unsigned char  kFile${index}[] = {\n        ${bytes}\n    };\n\n")
    string(APPEND entries "        StaticFile{ \"/${name}\", \"${type}\", view( kFile${index}, sizeof kFile${index}) },\n")
    math(EXPR index "${index} + 1")
endforeach()

file(CONFIGURE OUTPUT "${EMBED_OUTPUT}" @ONLY CONTENT [[
// Generated by cmake/EmbedFiles.cmake from framework/webui/static/ -- edit those, not this.
#include "static_content.hpp"

namespace webui
{
    namespace
    {
        auto view( const unsigned char * bytes, std::size_t size) -> std::string_view
        {
            return { reinterpret_cast<const char *>( bytes), size};
        }

@arrays@    }

    auto staticFiles() -> std::span<const StaticFile>
    {
        static const StaticFile  files[] = {
@entries@        };
        return files;
    }
}
]])
